### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by 787264137** [person594/regccrf-experiments#1]
2021-09-26 23:56:25| Preparing dev corpus...
2021-09-26 23:57:08| Instantiating CCRF...
2021-09-26 23:57:09| CCRF has 133 tags
2021-09-26 23:57:09| Starting Training...
2021-09-26 23:57:42| 1 200 169.98034282684327
2021-09-26 23:58:14| 1 400 104.24452308654786
2021-09-26 23:58:48| 1 600 100.76505264282227
2021-09-26 23:59:21| 1 800 95.0745164489746
2021-09-26 23:59:54| 1 1000 85.81955715179443
2021-09-27 00:00:27| 1 1200 95.86147197723389
2021-09-27 00:01:00| 1 1400 88.73686571121216
2021-09-27 00:01:33| 1 1600 79.58681606292724
2021-09-27 00:02:06| 1 1800 91.31070732116699
2021-09-27 00:02:39| 1 2000 89.64165632247925
2021-09-27 00:03:12| 1 2200 83.68744121551514
2021-09-27 00:03:45| 1 2400 71.16262254714965
2021-09-27 00:04:18| 1 2600 72.37540645599366
2021-09-27 00:04:52| 1 2800 76.39296867370605
2021-09-27 00:05:25| 1 3000 71.9068674659729
2021-09-27 00:05:58| 1 3200 64.31206956863403
2021-09-27 00:06:31| 1 3400 68.11742950439454
2021-09-27 00:07:04| 1 3600 58.21481056213379
2021-09-27 00:07:37| 1 3800 61.306538619995116
2021-09-27 00:08:09| 1 4000 60.13872232437134
2021-09-27 00:08:42| 1 4200 59.69763780593872
2021-09-27 00:09:16| 1 4400 66.74136613845825
2021-09-27 00:09:49| 1 4600 54.46299800872803
2021-09-27 00:10:22| 1 4800 65.70211612701416
2021-09-27 00:10:55| 1 5000 62.463439826965335
2021-09-27 00:10:55| Average loss: 79.9081577758789
2021-09-27 00:10:55| Evaluating on dev corpus...
Traceback (most recent call last):
  File "srl/srl.py", line 424, in <module>
    pred_bios = predict(tinydev_xys, bert, ccrf)
  File "srl/srl.py", line 244, in predict
    encoded = bert(x)
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/search/odin/zjf/srl/regccrf-experiments-master/srl/bert_wrapper.py", line 30, in forward
    output_window = self.bert(input_window)[0]
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 808, in forward
    embedding_output = self.embeddings(
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 124, in forward
    embeddings = self.LayerNorm(embeddings)
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 170, in forward
    return F.layer_norm(
  File "/root/miniconda2/envs/regccrf/lib/python3.8/site-packages/torch/nn/functional.py", line 2205, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA error: device-side assert triggered

beg for help....

**Comment by person594** [comment]
Hrm, I haven't seen this particular error before.  It seems that you can train fine, but have trouble at inference time with the layer_norm inside of roberta.  Normally that sort of error is caused by index errors, but I don't know why it would trigger from layer_norm...

To narrow things down a bit and try to exclude possibilities, could you tell me a bit about your setup?  Are you training on OntoNotes 2012, or a different dataset?  Did you make any changes anywhere in the code (i.e. to the tokenizer/roberta model).
Finally, what version of pytorch and huggingface are you using?
